find_package(OpenMP REQUIRED)
message(STATUS "ZLIB_LIBRARIES: ${ZLIB_LIBRARIES}")
message(STATUS "ZLIB_LIBRARIES: ${ZLIB_INCLUDE_DIRS}")
find_package(ZLIB REQUIRED)
if(ZLIB_FOUND)
    add_definitions(-DHAVE_LIBZ=1)
endif()
message(STATUS "ZLIB_LIBRARIES: ${ZLIB_LIBRARIES}")
message(STATUS "ZLIB_LIBRARIES: ${ZLIB_INCLUDE_DIRS}")
if(DEFINED ENV{BOOST_ROOT} AND DEFINED ENV{BOOSTROOT})
    if(NOT ENV{BOOST_ROOT} EQUAL ENV{BOOSTROOT})
        message(FATAL_ERROR "BOOST_ROOT and BOOSTROOT both defined, but don't match")
    endif()
elseif(DEFINED ENV{BOOST_ROOT} OR DEFINED ENV{BOOSTROOT})
    set(Boost_NO_SYSTEM_PATHS ON)
endif()
find_package(Boost 1.54.0 EXACT REQUIRED COMPONENTS serialization system thread )
if(HAVE_BOOST)
    add_definitions(-DHAVE_BOOST)
endif()
set(Boost_REQUESTED_LIBRARIES ${Boost_SERIALIZATION_LIBRARIES} ${Boost_SYSTEM_LIBRARIES} ${Boost_THREAD_LIBRARIES})
message(STATUS "Boost_REQUESTED_LIBRARIES: ${Boost_REQUESTED_LIBRARIES}")
message(STATUS "Boost_INCLUDE_DIRS: ${Boost_INCLUDE_DIRS}")
set(Boost_ALL_LIBS ${Boost_THREAD_LIBRARIES} ${Boost_LIBRARIES})
find_package(Eigen3 3 REQUIRED)
if(EIGEN3_FOUND)
    add_definitions(-DHAVE_EIGEN)
endif()
#TODO 1st: find bamlib in same manner as the m4 file
find_package(Samtools REQUIRED)
if(Samtools_FOUND)
    add_definitions(-DHAVE_BAM)
endif()
#TODO 2nd: find HTS_lib and fix code to use that instead
find_package(HTSlib REQUIRED)
#TODO add any universal flags, definitions, and libraries to these:
#CMAKE_REQUIRED_FLAGS = string of compile command line flags
#CMAKE_REQUIRED_DEFINITIONS = list of macros to define (-DFOO=bar)
#CMAKE_REQUIRED_INCLUDES = list of include directories
#CMAKE_REQUIRED_LIBRARIES = list of libraries to link
